import type { Survey } from "./schema";

export const mockSurveys: Survey[] = [
  {
    id: 1,
    name: "Juan Dela Cruz",
    age: 17,
    youthAgeGroup: "Child Youth",
    registeredSkVoter: false,
    registeredNationalVoter: false,
    votedLastElection: false,
    attendedKkAssembly: false,
    kkAssemblyFrequency: undefined,
    kkAssemblyReasonNo: "Not interested to attend",
    civilStatus: "Single",
    sex: "Male",
    educationalBackground: "High School Level",
    youthClassification: "In School Youth",
    workStatus: "Student",
  },
  {
    id: 2,
    name: "Maria Santos",
    age: 22,
    youthAgeGroup: "Core Youth",
    registeredSkVoter: true,
    registeredNationalVoter: true,
    votedLastElection: true,
    attendedKkAssembly: true,
    kkAssemblyFrequency: "3-4 times",
    kkAssemblyReasonNo: undefined,
    civilStatus: "Single",
    sex: "Female",
    educationalBackground: "College",
    youthClassification: "In School Youth",
    workStatus: "Student",
  },
  {
    id: 3,
    name: "Carlos Reyes",
    age: 27,
    youthAgeGroup: "Young Adult",
    registeredSkVoter: true,
    registeredNationalVoter: true,
    votedLastElection: true,
    attendedKkAssembly: false,
    kkAssemblyFrequency: undefined,
    kkAssemblyReasonNo: "There was no KK Assembly Meeting",
    civilStatus: "Married",
    sex: "Male",
    educationalBackground: "College",
    youthClassification: "Working Youth",
    workStatus: "Employed",
  },
  {
    id: 4,
    name: "Ana Lopez",
    age: 24,
    youthAgeGroup: "Core Youth",
    registeredSkVoter: false,
    registeredNationalVoter: true,
    votedLastElection: false,
    attendedKkAssembly: true,
    kkAssemblyFrequency: "1-2 times",
    kkAssemblyReasonNo: undefined,
    civilStatus: "Single",
    sex: "Female",
    educationalBackground: "High School Level",
    youthClassification: "Out of School Youth",
    workStatus: "Unemployed",
  },
  {
    id: 5,
    name: "Leo Navarro",
    age: 19,
    youthAgeGroup: "Core Youth",
    registeredSkVoter: false,
    registeredNationalVoter: false,
    votedLastElection: false,
    attendedKkAssembly: false,
    kkAssemblyFrequency: undefined,
    kkAssemblyReasonNo: "Not interested to attend",
    civilStatus: "Single",
    sex: "Male",
    educationalBackground: "High School Level",
    youthClassification: "In School Youth",
    workStatus: "Student",
  },
];

export default mockSurveys;
