import type { Survey } from "./schema";

export const mockSurveys: Survey[] = [
  {
    id: 1,
    firstName: "Juan",
    lastName: "Dela Cruz",
    middleName: "",
    suffix: "",
    birthdate: "2009-03-15",
    email: "juan@email.com",
    contactNumber: "",
    age: 17,
    location: "Purok 1",
    otherLocation: "",
    youthAgeGroup: "Child Youth",
    registeredSkVoter: false,
    registeredNationalVoter: false,
    votedLastElection: false,
    attendedKkAssembly: false,
    kkAssemblyFrequency: undefined,
    kkAssemblyReasonNo: "Not interested to attend",
    civilStatus: "Single",
    sex: "Male",
    educationalBackground: "High School Level",
    youthClassification: "In School Youth",
    specialNeedsType: "",
    workStatus: "Student",
  },
  {
    id: 2,
    firstName: "Maria",
    lastName: "Santos",
    middleName: "",
    suffix: "",
    birthdate: "2004-07-22",
    email: "maria@email.com",
    contactNumber: "",
    age: 22,
    location: "Purok 2",
    otherLocation: "",
    youthAgeGroup: "Core Youth",
    registeredSkVoter: true,
    registeredNationalVoter: true,
    votedLastElection: true,
    attendedKkAssembly: true,
    kkAssemblyFrequency: "3-4 times",
    kkAssemblyReasonNo: undefined,
    civilStatus: "Single",
    sex: "Female",
    educationalBackground: "College Graduate",
    youthClassification: "In School Youth",
    specialNeedsType: "",
    workStatus: "Student",
  },
  {
    id: 3,
    firstName: "Carlos",
    lastName: "Reyes",
    middleName: "",
    suffix: "",
    birthdate: "1999-11-08",
    email: "carlos@email.com",
    contactNumber: "",
    age: 27,
    location: "Purok 3",
    otherLocation: "",
    youthAgeGroup: "Young Adult",
    registeredSkVoter: true,
    registeredNationalVoter: true,
    votedLastElection: true,
    attendedKkAssembly: false,
    kkAssemblyFrequency: undefined,
    kkAssemblyReasonNo: "There was no KK Assembly Meeting",
    civilStatus: "Married",
    sex: "Male",
    educationalBackground: "College Graduate",
    youthClassification: "Working Youth",
    specialNeedsType: "",
    workStatus: "Employed",
  },
  {
    id: 4,
    firstName: "Ana",
    lastName: "Lopez",
    middleName: "",
    suffix: "",
    birthdate: "2002-05-18",
    email: "ana@email.com",
    contactNumber: "",
    age: 24,
    location: "Purok 4",
    otherLocation: "",
    youthAgeGroup: "Core Youth",
    registeredSkVoter: false,
    registeredNationalVoter: true,
    votedLastElection: false,
    attendedKkAssembly: true,
    kkAssemblyFrequency: "1-2 times",
    kkAssemblyReasonNo: undefined,
    civilStatus: "Single",
    sex: "Female",
    educationalBackground: "High School Level",
    youthClassification: "Out of School Youth",
    specialNeedsType: "",
    workStatus: "Unemployed",
  },
  {
    id: 5,
    firstName: "Leo",
    lastName: "Navarro",
    middleName: "",
    suffix: "",
    birthdate: "2007-09-12",
    email: "leo@email.com",
    contactNumber: "",
    age: 19,
    location: "Purok 5",
    otherLocation: "",
    youthAgeGroup: "Core Youth",
    registeredSkVoter: false,
    registeredNationalVoter: false,
    votedLastElection: false,
    attendedKkAssembly: false,
    kkAssemblyFrequency: undefined,
    kkAssemblyReasonNo: "Not interested to attend",
    civilStatus: "Single",
    sex: "Male",
    educationalBackground: "High School Level",
    youthClassification: "In School Youth",
    specialNeedsType: "",
    workStatus: "Student",
  },
];

export default mockSurveys;
